### ISSUE TITLE
FieldtypeOptions field returns unexpected values

### ISSUE THREAD

**Issue by webmanufaktur** [teppokoivula/Snippets#5]
_// this is fine_
{{page.fieldFieldtypeOptions}} returns _value id_

_// these are unexpected_
{{page.fieldFieldtypeOptions.value}} returns "Array" (just the word, not an actual array)
{{page.fieldFieldtypeOptions.title}} returns "Array" (just the word, not an actual array)

_// expected was_
{{page.fieldFieldtypeOptions.value}} returns _value1_
{{page.fieldFieldtypeOptions.title}} returns _title1_

fieldFieldtypeOptions setting is _single value_

**Options are defined like this**

1=value1|title1
2=value2|title2
3=value3|title3

**Comment by teppokoivula** [comment]
Latest version of the module (1.2.0) includes updates for page value handling, particularly for cases where properties with array type return values (any type of WireArray, or an actual array) are included. Due to the way values are fetched they are not exactly as described above, but pretty close.

Here's my test snippet:

```
<script>
console.log('test 1: {{page.test_options}}');
console.log('test 2: {{page.test_options.title}}');
console.log('test 3: {{page.test_options.value}}');
console.log('test 4: {{page.test_options.0.title}}');
console.log('test 5: {{page.test_page_field}}');
console.log('test 6: {{page.test_page_field.title}}');
console.log('test 7: {{page.test_page_field.0.title}}');
</script>
```

And here's the output I'm seeing:

```
test 1: 2
test 2: ["title2"]
test 3: ["value2"]
test 4: title2
test 5: 1148|1149
test 6: ["Tietoa meistä","Yhteystiedot"]
test 7: Tietoa meistä
```

I'm closing this issue for now, but let me know if there are still issues with this :)

**Comment by webmanufaktur** [comment]
Options work as expected now.
As some values and titles end in schema.org markup it's necessary to use the notation from test 4 or 7.
Awesome!
